[build]
  # No 'base' here. We handle the navigation in the command.
  command = "cd hackathon/pharmaguard_frontend && npm run build"
  publish = "hackathon/pharmaguard_frontend/.next"

[functions]
  # Path relative to the root of the repo
  directory = "hackathon/pharmaguard_backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/handler/:splat"
  status = 200